[WIP]トレンドタグの集計方法を変更した
bluenapoleon/mastodon pull request #19
Opened 2018-08-29 15:22 UTC by cormojs

@yakitama 表題の通り、トレンドタグの集計方法について集計するタイミングと計算式を変更しましたので、テストをお願いします。

#14 に対するPRです。

2018-09-02 01:23 UTC, fvh-P requested changes

2018-09-02 01:23 UTC, fvh-P commented on app/models/statuses_tag.rb
> +    def aggregate_tags_in(t: 20.minutes, until_t: Time.now.utc)
ここ、引数のデフォルト値を変更するのではなく、呼び出し側を
`aggregate_tags_in(t: 20.minutes)`
に変更するべきだと思います。

2018-09-02 14:23 UTC, fvh-P requested changes

2018-09-02 14:23 UTC, fvh-P commented on app/models/statuses_tag.rb
> +        aggregate_tags_in(20.min),
キーワード引数なので呼び出しもキーワードを使用して
`aggregate_tags_in(t: 20.minutes)`
になります。`20.min`ではなく`20.minutes`です。

2018-09-04 11:23 UTC, fvh-P approved these changes
OKだと思います。

2018-09-16 11:19 UTC, yakitama commented
動作確認しました。テストサーバーで動作中です。やきゅさん見たらなにか残しておいてください。

2018-09-18 13:29 UTC, YaQ00 commented
見ました。一度マージして運用後に変更描けたい部分はサイドPR作ります。マージ！

2018-09-18 13:30 UTC, merged